"""Arike URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LogoutView
from user.views import (
    HomeView,
    UserCreateView,
    log_in,
    StateView,
    CreateStateView,
    UpdateStateView,
    DeleteStateView,
    DetailStateView,
    DistrictView,
    CreateDistrictView,
    UpdateDistrictView,
    DeleteDistrictView,
    DetailDistrictView,
    LgsBodyView,
    CreateLgsBodyView,
    UpdateLgsBodyView,
    DeleteLgsBodyView,
    DetailLgsBodyView,
    WardView,
    CreateWardView,
    UpdateWardView,
    DeleteWardView,
    DetailWardView,
    FacilityView,
    CreateFacilityView,
    UpdateFacilityView,
    DeleteFacilityView,
    DetailFacilityView,
    PatientView,
    CreatePatientView,
    DeletePatientView,
    UpdatePatientView,
    DetailPatientView,
    FamilyDetailsView,
    CreateFamilyDetailsView,
    UpdateFamilyDetailsView,
    DeleteFamilyDetailsView,
    DetailFamilyDetailsView,
    DiseaseView,
    CreateDiseaseView,
    DeleteDiseaseView,
    UpdateDiseaseView,
    DetailDiseaseView,
    PatientDiseaseView,
    CreatePatientDiseaseView,
    DeletePatientDiseaseView,
    UpdatePatientDiseaseView,
    DetailPatientDiseaseView,
    VisitScheduleView,
    CreateVisitScheduleView,
    DeleteVisitScheduleView,
    UpdateVisitScheduleView,
    DetailVisitScheduleView,
    VisitDetailsView,
    CreateVisitDetailsView,
    DeleteVisitDetailsView,
    UpdateVisitDetailsView,
    DetailVisitDetailsView,
    TreatmentView,
    CreateTreatmentView,
    DeleteTreatmentView,
    UpdateTreatmentView,
    DetailTreatmentView,
    TreatmentNotesView,
    CreateTreatmentNotesView,
    DeleteTreatmentNotesView,
    UpdateTreatmentNotesView,
    DetailTreatmentNotesView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view()),
    path("login/", log_in, name='login'),
    path("logout/", LogoutView.as_view()),
    path("signup/", UserCreateView.as_view(),name='signin'),
    path("patient/", PatientView.as_view()),
    path("patient-create/",CreatePatientView.as_view()),
    path("patient-delete/<pk>",DeletePatientView.as_view()),
    path("patient-update/<pk>",UpdatePatientView.as_view()),
    path("patient-detail/<pk>",DetailPatientView.as_view()),
    path("state/", StateView.as_view()),
    path("state-create/",CreateStateView.as_view()),
    path("state-delete/<pk>",DeleteStateView.as_view()),
    path("state-update/<pk>",UpdateStateView.as_view()),
    path("state-detail/<pk>",DetailStateView.as_view()),
    path("district/", DistrictView.as_view()),
    path("district-create/",CreateDistrictView.as_view()),
    path("district-delete/<pk>",DeleteDistrictView.as_view()),
    path("district-update/<pk>",UpdateDistrictView.as_view()),
    path("district-detail/<pk>",DetailDistrictView.as_view()),
    path("lgsbody/", LgsBodyView.as_view()),
    path("lgsbody-create/",CreateLgsBodyView.as_view()),
    path("lgsbody-delete/<pk>",DeleteLgsBodyView.as_view()),
    path("lgsbody-update/<pk>",UpdateLgsBodyView.as_view()),
    path("lgsbody-detail/<pk>",DetailLgsBodyView.as_view()),
    path("ward/", WardView.as_view()),
    path("ward-create/",CreateWardView.as_view()),
    path("ward-delete/<pk>",DeleteWardView.as_view()),
    path("ward-update/<pk>",UpdateWardView.as_view()),
    path("ward-detail/<pk>",DetailWardView.as_view()),
    path("facility/", FacilityView.as_view()),
    path("facility-create/",CreateFacilityView.as_view()),
    path("facility-delete/<pk>",DeleteFacilityView.as_view()),
    path("facility-update/<pk>",UpdateFacilityView.as_view()),
    path("facility-detail/<pk>",DetailFacilityView.as_view()),
    path("familydetails/", FamilyDetailsView.as_view()),
    path("familydetails-create/",CreateFamilyDetailsView.as_view()),
    path("familydetails-delete/<pk>",DeleteFamilyDetailsView.as_view()),
    path("familydetails-update/<pk>",UpdateFamilyDetailsView.as_view()),
    path("familydetails-detail/<pk>",DetailFamilyDetailsView.as_view()),
    path("disease/", DiseaseView.as_view()),
    path("disease-create/",CreateDiseaseView.as_view()),
    path("disease-delete/<pk>",DeleteDiseaseView.as_view()),
    path("disease-update/<pk>",UpdateDiseaseView.as_view()),
    path("disease-detail/<pk>",DetailDiseaseView.as_view()),
    path("patientdisease/", PatientDiseaseView.as_view()),
    path("patientdisease-create/",CreatePatientDiseaseView.as_view()),
    path("patientdisease-delete/<pk>",DeletePatientDiseaseView.as_view()),
    path("patientdisease-update/<pk>",UpdatePatientDiseaseView.as_view()),
    path("patientdisease-detail/<pk>",DetailPatientDiseaseView.as_view()),
    path("visitschedule/", VisitScheduleView.as_view()),
    path("visitschedule-create/",CreateVisitScheduleView.as_view()),
    path("visitschedule-delete/<pk>",DeleteVisitScheduleView.as_view()),
    path("visitschedule-update/<pk>",UpdateVisitScheduleView.as_view()),
    path("visitschedule-detail/<pk>",DetailVisitScheduleView.as_view()),
    path("visitdetails/", VisitDetailsView.as_view()),
    path("visitdetails-create/",CreateVisitDetailsView.as_view()),
    path("visitdetails-delete/<pk>",DeleteVisitDetailsView.as_view()),
    path("visitdetails-update/<pk>",UpdateVisitDetailsView.as_view()),
    path("visitdetails-detail/<pk>",DetailVisitDetailsView.as_view()),
    path("treatment/", TreatmentView.as_view()),
    path("treatment-create/",CreateTreatmentView.as_view()),
    path("treatment-delete/<pk>",DeleteTreatmentView.as_view()),
    path("treatment-update/<pk>",UpdateTreatmentView.as_view()),
    path("treatment-detail/<pk>",DetailTreatmentView.as_view()),
    path("treatmentnotes/", TreatmentNotesView.as_view()),
    path("treatmentnotes-create/",CreateTreatmentNotesView.as_view()),
    path("treatmentnotes-delete/<pk>",DeleteTreatmentNotesView.as_view()),
    path("treatmentnotes-update/<pk>",UpdateTreatmentNotesView.as_view()),
    path("treatmentnotes-detail/<pk>",DetailTreatmentNotesView.as_view()),
]