# Generated by Django 4.0.1 on 2022-03-13 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 3, 24, 21, 732344, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 3, 24, 21, 732344, tzinfo=utc)),
        ),
    ]
