# Generated by Django 4.0.1 on 2022-03-11 03:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_patient_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 3, 1, 56, 528557, tzinfo=utc), null=True),
        ),
    ]
