# Generated by Django 4.0.1 on 2022-03-11 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_patient_expired_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lgsbody',
            old_name='lsg_body_code',
            new_name='lgs_body_code',
        ),
        migrations.AlterField(
            model_name='patient',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 7, 35, 33, 830476, tzinfo=utc), null=True),
        ),
    ]
