# Generated by Django 4.0.1 on 2022-03-12 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_managers_rename_username_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2022, 3, 12)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 11, 29, 8, 543458, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 16, 59, 8, 545452)),
        ),
    ]
