# Generated by Django 4.0.1 on 2022-03-12 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_patient_expired_time_alter_visitschedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isFirst',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lgsbody',
            name='kind',
            field=models.CharField(choices=[('1', 'Grama Panchayath'), ('2', 'Block Panchayath'), ('3', 'District Panchayath'), ('4', 'Nagar Panchayath'), ('10', 'Municipality'), ('20', 'Corporation'), ('50', 'Others')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 14, 51, 14, 361799, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 14, 51, 14, 361799, tzinfo=utc)),
        ),
    ]
